---
title: "K-Means"
author: "Seung Ah Ha, Jaymo Kim, Wonbin Song"
output: pdf_document
---

```{r}
install.packages('rattle')
data(wine, package="rattle")

assign <- function(data){
  mat.data <- data.matrix(data)
  n.row <- nrow(mat.data)
  n.col <- ncol(mat.data)
  
  # randomly assigning a group label
  G.label <- rep(0,n.row)
  for(i in 1:n.row){
    G.label[i] <- sample(1:3,1)
  }
  new.data <- cbind(G.label,mat.data)
  
  # calculates the group centres
  mat.mu <- matrix(0,3,(n.col+1))
  for(j in 2:(n.col+1)){
    for(i in 1:3){
      mat.mu[i,j] <- mean(new.data[G.label==i,j])
    }
  }
  mat.mu[1,1]<- 1
  mat.mu[2,1]<- 2
  mat.mu[3,1]<- 3
  
  distance <- matrix(0,n.row,3)
  new.label <- rep(0,n.row)
  for(i in 1:n.row){
    for(j in 2:(n.col+1)){
      distance[i,1] <- sqrt(sum((new.data[i,j]-mat.mu[1,j])^2))
      distance[i,2] <- sqrt(sum((new.data[i,j]-mat.mu[2,j])^2))
      distance[i,3] <- sqrt(sum((new.data[i,j]-mat.mu[3,j])^2))
    }
  }
  for (i in 1:n.row){
    new.label[i] <- which(distance[i,]==min(distance[i,]))
  }
  return(new.label)
}

re.assign <- function(data){
  mat.data <- data.matrix(data)
  n.row <- nrow(mat.data)
  n.col <- ncol(mat.data)
  
  new.data <- cbind(assign(data),mat.data)
  mat.mu <- matrix(0,3,(n.col+1))
  for(j in 2:(n.col+1)){
    for(i in 1:3){
      mat.mu[i,j] <- mean(new.data[new.data[,1]==i,j])
    }
  }
  mat.mu[1,1]<- 1
  mat.mu[2,1]<- 2
  mat.mu[3,1]<- 3
  
  distance <- matrix(0,n.row,3)
  new.label <- rep(0,n.row)
  for(i in 1:n.row){
    for(j in 2:(n.col+1)){
      distance[i,1] <- sqrt(sum((new.data[i,j]-mat.mu[1,j])^2))
      distance[i,2] <- sqrt(sum((new.data[i,j]-mat.mu[2,j])^2))
      distance[i,3] <- sqrt(sum((new.data[i,j]-mat.mu[3,j])^2))
    }
  }
  for (i in 1:n.row){
    new.label[i] <- which(distance[i,]==min(distance[i,]))
  }
  return(new.label)
}


```


```{r}
install.packages('rattle')
data(wine, package="rattle")

# assign <- function(data){
initial <- function(data)
{
    mat.data <- data.matrix(data)
    n.row <- nrow(mat.data)
    n.col <- ncol(mat.data)
    
    # randomly assigning a group label
    G.label <- rep(0,n.row)
    for(i in 1:n.row){
        G.label[i] <- sample(1:3,1)
    }
    new.data <- cbind(G.label,mat.data)
    
    new.l <- foo(mat.data, n.row, n.col, G.label, new.data)
    n.iter <- 1
    while(any(new.l != G.label))
    {
        G.label <- new.l
        new.l <- foo(mat.data, n.row, n.col, G.label, new.data)
        n.iter <- n.iter + 1
    }
    return(list(number_of_iter = n.iter, new_group = new.l))
}

foo <- function(mat.data, n.row, n.col, G.label, new.data)
{
    # calculates the group centres
    mat.mu <- matrix(0,3,(n.col+1))
    for(j in 2:(n.col+1)){
        for(i in 1:3){
            mat.mu[i,j] <- mean(new.data[G.label==i,j])
        }
    }
    mat.mu[1,1]<- 1
    mat.mu[2,1]<- 2
    mat.mu[3,1]<- 3
    
    distance <- matrix(0,n.row,3)
    new.label <- rep(0,n.row)
    for(i in 1:n.row){
        for(j in 2:(n.col+1)){
            distance[i,1] <- sqrt(sum((new.data[i,j]-mat.mu[1,j])^2))
            distance[i,2] <- sqrt(sum((new.data[i,j]-mat.mu[2,j])^2))
            distance[i,3] <- sqrt(sum((new.data[i,j]-mat.mu[3,j])^2))
        }
    }
    
    for (i in 1:n.row){
        new.label[i] <- which(distance[i,]==min(distance[i,]))
    }
    
    return(new.label)
}


initial(wine) 
kmeans(wine, 3)

```

